### ISSUE TITLE
Problem when click start

### ISSUE THREAD

**Issue by petbaik** [CERNatschool/getting-started#1]
Here's what i get when i click start 
Failed to open a session for the virtual machine mymachine_Xubuntu-14-04;.

VT-x is not available. (VERR_VMX_NO_VMX).

Result Code: E_FAIL (0x80004005)
Component: Console
Interface: IConsole {8ab7c520-2442-4b66-8d74-4ff1e195d2b6}

**Comment by twhyntie** [comment]
Hi @petbaik,

Googling the error message throws up this for me: <https://forums.virtualbox.org/viewtopic.php?f=6&t=58820> - does this ring any bells?

What system are you running VirtualBox on? _Control Panel_ -> _System Properties_ should let you know if you're running a 32-bit or 64-bit system.

Thanks, @twhyntie

**Comment by twhyntie** [comment]
I take it this has worked - closing the issue.

Thanks, Tom
