### ISSUE TITLE
Memory size, Creating a Xubuntu 14.04 Virtual Machine with VirtualBox

### ISSUE THREAD

**Issue by jersonzc** [CERNatschool/getting-started#2]
Hi!
I spot a mistake when you said "Move the slider as far to the right in the green band that you can ... ".
Allocating memory goes from green to red band that is from less to greater memory size.

**Comment by twhyntie** [comment]
Hi, thanks for raising this issue.

I've looked at the process again and I think the wording in the guide is correct - you want to allocate the VM the most memory you can (i.e. move the slider to as far to the right as you can - moving the slider to the right increases the memory allocated to the VM) but without taking up too much memory on your VM (which your host machine needs to run). This is indicated by the red band, so you **don't want** to move the slider so far to the right that it moves into this red band.

Ultimately you have to use your own judgement but I think the wording is correct as it is - I will close the issue but if you have suggestions for a better wording please let us know.

Thanks, Tom
