### ISSUE TITLE
Incomplete LaTeX documentation

### ISSUE THREAD

**Issue by jjsanderson** [CERNatschool/getting-started#3]
The "Installing LaTeX on Xubuntu 14.04" document cuts off in mid sentence:

> To use the font in a LaTeX document:

It's also not clear what additional fonts we should be installing at this stage.

**Comment by twhyntie** [comment]
Hi @jjsanderson 

Apologies, this has all been superceded by our swanky new GridPP CernVM system which handles all of the LaTeX stuff for you. Instructions here:

https://www.gridpp.ac.uk/userguide/

I'll take these instructions down and close the issue, sorry.

Cheers, @twhyntie

**Comment by jjsanderson** [comment]
No problem - is there another introductory document I should be following?

That gridpp link is giving a certificate error for me, by the way.

**Comment by twhyntie** [comment]
Hello @jjsanderson ;-)

For creating a GridPP VM (which can be used for CERN@school coding), see:

https://www.gridpp.ac.uk/userguide/gridpp-cernvm/gridpp-cernvm.html

(But it's worth going from the beginning...)

Re. the certificate error, are you using Safari on a Mac perchance? We think we've ironed out all the bugs on Firefox and Chrome. If you could give more details on the UserGuide GitHub page that would be great:

https://github.com/gridpp/user-guides/issues

Thanks as ever, @twhyntie
